name: CD
on:
  push:
    branches: [ master ]

jobs:
  deployStaticSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace Git HASH
        run: sed -i 's/COMMIT_HASH/${{ GITHUB_SHA }}/g' index.html
      - name: Deploy to heady-believe.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'heady-believe.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
